name: ff_drop_down_list
description: A customizable dropdown widget supporting single/multiple selection, integrated search in a bottom sheet, generic support for flexible, type-safe handling of custom data.
repository: https://github.com/AndrewMast/ff_drop_down_list
issue_tracker: https://github.com/AndrewMast/ff_drop_down_list/issues

version: 0.0.5

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
